[package]
name = "simple-stopwatch"
version = "0.1.0"
authors = ["Huw Bowles <huw.bowles@gmail.com>"]
description = "Minimal stopwatch for rust, returns float values"
license = "MIT"

[dependencies]

time = "0.1.39"
